---
# This role contains tasks for configuring and starting clusterm service

- name: copy shell script for starting collins
  template: src=collins.j2 dest=/usr/bin/collins.sh mode=u=rwx,g=rx,o=rx
  tags:
    - prebake-for-dev

- name: copy systemd units for collins
  copy: src=collins.service dest=/etc/systemd/system/collins.service
  tags:
    - prebake-for-dev

- name: pull collins container image
  shell: docker pull {{ collins_image }}
  tags:
    - prebake-for-dev

- name: start collins
  service: name=collins state=started

- name: download clusterm
  get_url:
    validate_certs: "{{ validate_certs }}"
    url: "{{ contiv_cluster_src_file }}" 
    dest: "{{ contiv_cluster_dest_file }}"
    force: no
  register: download_result

- name: install clusterm
  shell: tar vxjf {{ contiv_cluster_dest_file }} 
  args:
    chdir: /usr/bin/
  when: download_result | changed 

- name: copy environment file for clusterm
  copy: src=clusterm dest=/etc/default/clusterm

- name: copy systemd units for clusterm
  copy: src=clusterm.service dest=/etc/systemd/system/clusterm.service

- name: start clusterm
  service: name=clusterm state=started
