---
# This role contains tasks for configuring and starting swarm service

- name: download and install swarm
  get_url:
    validate_certs: "{{ validate_certs }}"
    url: https://cisco.box.com/shared/static/0txiq5h7282hraujk09eleoevptd5jpl
    dest: /usr/bin/swarm
    mode: u=rwx,g=rx,o=rx
    force: no
  tags:
    - prebake-for-dev

- name: copy the swarm start/stop script
  template: src=swarm.j2 dest=/usr/bin/swarm.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for swarm
  copy: src=swarm.service dest=/etc/systemd/system/swarm.service

- name: start swarm
  shell: systemctl daemon-reload && systemctl start swarm
