---
# This role contains tasks for configuring and starting etcd service

- name: download etcd v2.1.1
  get_url:
    validate_certs: "{{ validate_certs }}"
    url: https://github.com/coreos/etcd/releases/download/v2.1.1/etcd-v2.1.1-linux-amd64.tar.gz
    dest: /tmp/etcd-v2.1.1-linux-amd64.tar.gz
    force: no
  tags:
    - prebake-for-dev

- name: install etcd
  shell: creates=/usr/bin/etcd tar vxzf /tmp/etcd-v2.1.1-linux-amd64.tar.gz && mv etcd-v2.1.1-linux-amd64/etcd* /usr/bin
  tags:
    - prebake-for-dev

- name: copy the etcd start/stop script
  template: src=etcd.j2 dest=/usr/bin/etcd.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for etcd
  copy: src=etcd.service dest=/etc/systemd/system/etcd.service

- name: Open etcd client port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "etcd"
#  when: "'etcd' not in iptablesrules.stdout"
#  notify:
#    - Save iptables rules
  with_items:
    - "{{ etcd_client_port1 }}"
    - "{{ etcd_client_port2 }}"
    - "{{ etcd_peer_port1 }}"
    - "{{ etcd_peer_port2 }}"

- name: start etcd
  service: name=etcd state=started
