- name: Create temp directory for building v2plugin
  tempfile: state=directory suffix=-v2plugin
  register: v2plugin_temp_dir

- block:
    - name: Allow Docker to read the tmpdir
      file: path={{ v2plugin_temp_dir.path }} group=docker mode=750

    - name: Create v2plugin rootfs directory
      file: state=directory path={{ v2plugin_temp_dir.path }}/rootfs

    - name: Unpack v2plugin from local archive
      unarchive:
        src: "/var/contiv_cache/{{ contiv_v2plugin_tar_filename }}"
        dest: "{{ v2plugin_temp_dir.path }}/rootfs/"

    - name: Copy config.json for plugin container
      copy: src=/var/contiv_cache/config.json dest={{ v2plugin_temp_dir.path }}

    - name: Create v2plugin from exploded archive
      shell: >
        docker plugin create {{ contiv_v2plugin_image }}
        {{ v2plugin_temp_dir.path }}

    - name: Set v2plugin settings
      shell: >
        docker plugin set {{ contiv_v2plugin_image }}
        CONTIV_ROLE={{ (run_as == 'master') | ternary('netmaster', 'netplugin') }}
        CONTIV_NETPLUGIN_CONTROL_IP={{node_addr}}
        CONTIV_NETPLUGIN_FORWARD_MODE={{ fwd_mode }}
        CONTIV_NETPLUGIN_MODE=docker
        CONTIV_NETPLUGIN_VXLAN_PORT={{vxlan_port}}
        CONTIV_NETPLUGIN_VLAN_UPLINKS={{netplugin_if}}
        CONTIV_NETPLUGIN_NET_MODE={{ (fwd_mode == 'bridge') | ternary('vlan', 'vxlan') }}
        {{ (cluster_store_driver == 'etcd') | ternary('CONTIV_NETPLUGIN_ETCD_ENDPOINTS', 'CONTIV_NETPLUGIN_CONSUL_ENDPOINTS') }}={{ cluster_store_url }}
        CONTIV_NETMASTER_NET_MODE={{ (fwd_mode == 'bridge') | ternary('vlan', 'vxlan') }}
        CONTIV_NETMASTER_PLUGIN_NAME={{contiv_v2plugin_image}}
        CONTIV_NETMASTER_FORWARD_MODE={{ fwd_mode }}
        CONTIV_NETMASTER_INTERNAL_ADDRESS={{node_addr}}:{{netmaster_port}}
        CONTIV_NETMASTER_MODE=docker
        {{ (cluster_store_driver == 'etcd') | ternary('CONTIV_NETMASTER_ETCD_ENDPOINTS', 'CONTIV_NETMASTER_CONSUL_ENDPOINTS') }}={{ cluster_store_url }}

  always:
    - name: Remove v2plugin rootfs
      file: state=absent path={{ v2plugin_temp_dir.path }}

- name: start v2plugin
  systemd: name=v2plugin state=started
