---
# This role contains tasks for starting docker plugin service

- name: for v2 plugin, extract netctl binaries
  shell: tar vxjf {{ contiv_network_dest_file }} netctl contrib/completion/bash/netctl
  args:
    chdir: /usr/bin/contiv/netplugin

- name: create the directories needed for ovs
  file: state=directory path={{ item }}
  with_items:
    - "/etc/openvswitch"
    - "/var/log/openvswitch"

- name: check if v2plugin has been installed on {{ run_as }} nodes
  shell: docker plugin ls | grep -n {{ contiv_v2plugin_image }}
  register: v2plugin_installed
  changed_when: no
  ignore_errors: True

- name: check if v2plugin archive is in the contiv_cache
  local_action: stat path=/var/contiv_cache/{{ contiv_v2plugin_tar_filename }} follow=yes
  register: v2plugin_archive_stat

- name: install v2plugin on {{ run_as }} nodes from dockerhub
  shell: >
    /usr/bin/docker plugin install --grant-all-permissions {{contiv_v2plugin_image}}
    CONTIV_ROLE={{ (run_as == 'master') | ternary('netmaster', 'netplugin') }}
    CONTIV_NETPLUGIN_CONTROL_IP={{node_addr}}
    CONTIV_NETPLUGIN_FORWARD_MODE={{ fwd_mode }}
    CONTIV_NETPLUGIN_MODE=docker
    CONTIV_NETPLUGIN_VXLAN_PORT={{vxlan_port}}
    CONTIV_NETPLUGIN_VLAN_UPLINKS={{netplugin_if}}
    CONTIV_NETPLUGIN_NET_MODE={{ (fwd_mode == 'bridge') | ternary('vlan', 'vxlan') }}
    {{ (cluster_store_driver == 'etcd') | ternary('CONTIV_NETPLUGIN_ETCD_ENDPOINTS', 'CONTIV_NETPLUGIN_CONSUL_ENDPOINTS') }}={{ cluster_store_url }}
    CONTIV_NETMASTER_NET_MODE={{ (fwd_mode == 'bridge') | ternary('vlan', 'vxlan') }}
    CONTIV_NETMASTER_PLUGIN_NAME={{contiv_v2plugin_image}}
    CONTIV_NETMASTER_FORWARD_MODE={{ fwd_mode }}
    CONTIV_NETMASTER_INTERNAL_ADDRESS={{node_addr}}:{{netmaster_port}}
    CONTIV_NETMASTER_MODE=docker
    {{ (cluster_store_driver == 'etcd') | ternary('CONTIV_NETMASTER_ETCD_ENDPOINTS', 'CONTIV_NETMASTER_CONSUL_ENDPOINTS') }}={{ cluster_store_url }}
  when:
    - v2plugin_installed|failed
    - not v2plugin_archive_stat.stat.exists

- name: copy v2plugin.sh file
  copy: src=v2plugin.sh dest=/usr/bin/v2plugin.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for v2plugin
  copy: src=v2plugin.service dest=/etc/systemd/system/v2plugin.service

- name: enable v2plugin
  systemd: name=v2plugin enabled=yes

- name: include v2plugin install from contiv_cache
  include: v2plugin_local_install.yml
  when:
    - v2plugin_installed|failed
    - v2plugin_archive_stat.stat.exists
  static: no
