- name: Create temp directory for building v2plugin
  tempfile: state=directory suffix=-v2plugin
  register: v2plugin_temp_dir

- block:
    - name: Allow Docker to read the tmpdir
      file: path={{ v2plugin_temp_dir.path }} group=docker mode=750

    - name: Create v2plugin rootfs directory
      file: state=directory path={{ v2plugin_temp_dir.path }}/rootfs

    - name: Unpack v2plugin from local archive
      unarchive:
        src: "/var/contiv_cache/{{ contiv_v2plugin_tar_filename }}"
        dest: "{{ v2plugin_temp_dir.path }}/rootfs/"

    - name: Copy config.json for plugin container
      copy: src=/var/contiv_cache/config.json dest={{ v2plugin_temp_dir.path }}

    - name: Create v2plugin from exploded archive
      shell: >
        docker plugin create {{ contiv_v2plugin_image }}
        {{ v2plugin_temp_dir.path }}

    - name: Set v2plugin settings
      shell: >
        docker plugin set {{ contiv_v2plugin_image }}
        ctrl_ip={{ node_addr }}
        control_url={{ node_addr }}:{{ netmaster_port }}
        vxlan_port={{ vxlan_port }}
        iflist={{ netplugin_if }}
        plugin_name={{ contiv_v2plugin_image }}
        cluster_store={{ cluster_store }}
        plugin_role={{ run_as }}
        fwd_mode={{ fwd_mode }}

  always:
    - name: Remove v2plugin rootfs
      file: state=absent path={{ v2plugin_temp_dir.path }}

- name: start v2plugin
  systemd: name=v2plugin state=started
