---
# This play contains tasks for cleaning up ucp

- name: stop ucp
  service: name=ucp state=stopped

- name: cleanup ucp files from remote
  file: name="{{ ucp_remote_dir }}/{{ item }}" state=absent
  with_items:
    - "{{ ucp_fingerprint_file }}"
    - "{{ ucp_instance_id_file }}"
    - "{{ ucp_fifo_file }}"
