---
# This play contains tasks for cleaning up docker

- name: remove all containers
  shell: unset DOCKER_HOST && docker rm -f -v $(docker ps -a -q)
  when: docker_reset_container_state == true

- name: remove all images
  shell: unset DOCKER_HOST && docker rmi -f $(docker images -q)
  when: docker_reset_image_state == true

- name: stop docker
  service: name=docker state=stopped

- name: stop docker tcp socket
  service: name=docker-tcp.socket state=stopped

- name: cleanup iptables for docker
  shell: iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ docker_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ docker_api_port }}"
