---
# This role contains tasks for configuring and starting docker service

# XXX: figure a way to download a specific docker version
- name: install docker
  shell: creates=/usr/bin/docker curl https://get.docker.com | bash
  tags:
    - prebake-for-dev

- name: create docker daemon's config directory
  file: path=/etc/systemd/system/docker.service.d state=directory
  tags:
    - prebake-for-dev

- name: setup docker daemon's environment
  template: src=env.conf.j2 dest=/etc/systemd/system/docker.service.d/env.conf
  tags:
    - prebake-for-dev

- name: copy systemd units for docker(enable cluster store) (debian)
  template: src=docker-svc.j2 dest=/lib/systemd/system/docker.service
  when: ansible_os_family == "Debian"

- name: copy systemd units for docker(enable cluster store) (redhat)
  template: src=docker-svc.j2 dest=/usr/lib/systemd/system/docker.service
  when: ansible_os_family == "RedHat"

- name: copy systemd units for docker tcp socket settings
  template: src=docker-tcp.j2 dest=/etc/systemd/system/docker-tcp.socket
  register: docker_tcp_socket

  # tcp socket service requires docker service to be started after it
- name: start docker tcp socket service
  shell: sudo systemctl stop docker && sudo systemctl start docker-tcp.socket && sudo systemctl start docker
  when: docker_tcp_socket | changed

- name: remove the docker key file, if any. It shall be regenerated by docker on restart
  file: name=/etc/docker/key.json  state=absent

# XXX: service module doesn't do daemon-reload yet, so need to use shell module here
# https://github.com/ansible/ansible-modules-core/issues/191
- name: restart docker
  #service: name=docker state=restarted
  shell: sudo systemctl daemon-reload && sudo systemctl restart docker
  tags:
    - prebake-for-dev

- name: install docker-compose
  pip: name=docker-compose state=latest extra_args=--upgrade
  tags:
    - prebake-for-dev
