- name: upgrade system (redhat)
  yum:
    update_cache: true
    name: '*'
    state: latest

# install epel-release first to ensure the extra packages can be installed later
- name: install epel release package (redhat)
  yum:
    name: epel-release

- name: install base packages (redhat)
  yum:
    name: "{{ item }}"
  with_items:
    - ntp
    - unzip
    - bzip2
    - vim
    - curl
    - git
    - mercurial
    - gcc
    - perl
    - librbd1-devel
    - lshw
    - python-pip
    - python-requests # XXX required by ceph repo, but it has a bad package on it

- name: install and start ntp
  shell: systemctl enable ntpd

- name: install python-crypto
  yum: name=python-crypto state=present
  register: python_crypto_result
  ignore_errors: yes

- name: remove python crypt egg file to work-around https://bugs.centos.org/view.php?id=9896&nbn=2
  shell: rm -rf /usr/lib64/python2.7/site-packages/pycrypto-2.6.1-py2.7.egg-info
  when: python_crypto_result.msg == "Error unpacking rpm package python-crypto-2.6.1-1.el7.centos.x86_64\n"

- name: install ansible (redhat)
  yum: name=ansible state=present
